### ISSUE TITLE
Google Message - Old build detected

### ISSUE THREAD

**Issue by it-joshua21** [kelyvin/Android-Messages-For-Desktop#79]
Hi Everyone, I keep receiving this error on my Google Message Desktop app. (This app built a long time ago. Nativefier uses the Chrome browsesr (through Electron), and it is insecure to keep using an old version of it. Please upgrade Nativefier and rebuild this app.)

I've installed the latest nodejs
Download the latest version:
https://github.com/kelyvin/Google-Messages-For-Desktop?tab=readme-ov-file

Run the following command
npm install -g nativefier@latest
npm run windows

I got this error from my command. 
    fn(internalBinding)(nm.exports, cachingRequire, nm, nm.filename, '<no dirname available>')
                       ^
ReferenceError: primordials is not defined
    at fs.js:44:5
    at req_ (C:\Users\Monika\Downloads\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Monika\Downloads\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Monika\Downloads\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Monika\Downloads\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
___________________________________________________________________

Issue:

![image](https://github.com/kelyvin/Google-Messages-For-Desktop/assets/146563902/0c57ebff-d687-4d24-bcd5-34cd6a0ab981)

**Comment by p1r473** [comment]
I get this too

**Comment by HolidayLighting** [comment]
I am getting this too

![image](https://github.com/user-attachments/assets/fa0fdcb3-1cd6-41a5-a06e-4a07e212b07f)

**Comment by 2loki4u** [comment]
I could be wrong, but from what I can tell, this project is more or less abandoned. I found an alternative though, which has been regularly updated and works well. Check this option out - I've been using it a year or more at this point without incident: https://github.com/OrangeDrangon/android-messages-desktop

![Screenshot 2024-08-19 090157](https://github.com/user-attachments/assets/7d44b389-d91d-47bb-868d-1fd3766bb43c)

**Comment by Lyqed** [comment]
> I could be wrong, but from what I can tell, this project is more or less abandoned. I found an alternative though, which has been regularly updated and works well. Check this option out - I've been using it a year or more at this point without incident: https://github.com/OrangeDrangon/android-messages-desktop
> 
> ![Screenshot 2024-08-19 090157](https://github.com/user-attachments/assets/7d44b389-d91d-47bb-868d-1fd3766bb43c)

thanks for sharing

**Comment by Supastyles** [comment]
I looked around online and found some info that lead me to this (One time):

```powershell
nativefier --upgrade "C:\......\google-messages-windows_v1.4.2\Google Messages-win32-x64\resources\app" --verbose`
``` 

I then created a shortcut using powershell and left it in the DIR for the future as I've read comments going back a few years with this issue. **Verbose** will tell you what went wrong if it goes wrong.

If you interested in that (future prep):

```powershell
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoExit -ExecutionPolicy Bypass -Command "nativefier --upgrade C:\......\google-messages-windows_v1.4.2\Google Messages-win32-x64\resources\app" --verbose"
``` 

**NoExit** will leave the window open so you can see the instructions if there are issues(goes along with **Verbose**.  you can remove **Verbose** and or **NoExit** from each string if you want.

I am no expert in NodeJS, nativefier or much else so I can't troubleshoot this if it doesn't work for you.  Just that it worked for me.

[Original reddit replythat lead to my path to the above solution](https://www.reddit.com/r/fairphone/comments/x7kxn6/comment/mpmf2v3/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)


Hope this helps out some people!
